export BIOINFOCONDA_OLDPWD="${BIOINFO_ROOT}/prj"

# Input: an absolute path
# Output: the project contained in that path, if any
function extract_prj
{
        if [[ $1 != "${BIOINFO_ROOT}/prj"* ]]; then
                return 1
        fi

        if [ "$1" == "$BIOINFO_ROOT/prj" ]; then
                echo $BIOINFO_ROOT/prj
        else
                echo $1 | cut -d '/' -f 4
        fi

        return 0
}

# Input: a relative path
# Output: the absolute path
function absolutise
{
        if [[ $1 == "/"* ]]; then
                echo $1
                return 0
        fi

        abs_path=$PWD
        rel_path=`echo $1 | sed 's#^./##'`

        for d in `echo $rel_path | cut -d '/' -f 1- --output-delimiter=' '`; do
                if [ "$d" == ".." ]; then
                        abs_path=`dirname $abs_path`
                else
                        abs_path=$abs_path"/"$d
                fi
        done

        echo $abs_path
        return 0
}

# Updates BIOINFOCONDA_OLWPWD
function cd
{
        # Find current project, if any
        cur_prj=""
        if extract_prj $PWD > /dev/null; then
                cur_prj=`extract_prj $PWD`
        fi

        # Find new project (exclude cd options), if any
        new_prj=""
        for p in $*; do
                if [[ $p != "-"* ]] && extract_prj $(absolutise $p) > /dev/null; then
                        dest=$p
                        new_prj=`extract_prj $(absolutise $dest)`
                fi
        done

        # If we are entering another project...
        if [ "$new_prj" != "" ]; then
                # ...From another project
                if [ "$cur_prj" != "" ] && [ $cur_prj != $new_prj ]; then
                        BIOINFOCONDA_OLDPWD=$PWD
                fi
        # Elif we come out to the outside world...
        elif [ "$new_prj" == "" ]; then
                # ...From a project
                if [ "$cur_prj" != "" ]; then
                        BIOINFOCONDA_OLDPWD=$PWD
                fi
        fi

        builtin cd "$@"
        return $?
}

# Note that in cdp we use the cd function we defined above, therefore we 
# need not worry about updating BIOINFOCONDA_OLDPWD
function cdp
{
        prj_root=${BIOINFO_ROOT}/prj

        if [ "$#" == "0" ]; then
                cd $prj_root
        elif [ "$#" == "1" ]; then
                if [ $1 == "-" ]; then
                        cd $BIOINFOCONDA_OLDPWD
                else
                        cd $prj_root/$1
                fi
        else
                echo "ERROR: Too many arguments."
                echo "Usage: cdp [prjname]"
                return 1
        fi

        return $?
}

